config/routes.rb
Rails.application.routes.draw do
  get 'days/index'

  devise_for :users
  resources :days do
    get :admin, on: :collection
    get :adminShow, on: :collection
  end

resources :days
  get 'home/index'
  root 'home#index'
  get 'days/show'
  get 'days/admin', to: 'days#admin', as: :admin
  put 'days/:id', to: 'days#update'
  patch 'days/:id', to: 'days#update'


  post 'days/new'
end

app/models/days.rb
class Days < ActiveRecord::Base
  belongs_to :users

  def subtract(left, taken)
    left = left - taken
    return left
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :days

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  respond_to :html, :json
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def pto
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_filter :authenticate_user!

  def index
    @days = Days.where(user_id:current_user.id).last
  end

  def new
    @day = Days.where(user_id:current_user.id).last
    @days = Days.new
  end

  def create
    @days = Days.new(days_params)
    @days.user_id = current_user.id
    @days.name = current_user.name
    @day = Days.where(user_id:current_user.id).last
    @days.daysLeft = @day.daysLeft - @days.daysTaken.to_i
    @day.save
    if @days.save
      redirect_to new_day_path
    else
      redirect_to day_path
    end
  end

  def show
    @days = Days.where(user_id:current_user.id)
    @users = User.all
  end

  def admin
    @user = current_user
    if @user.admin == true
      @days = Days.all
      @users = User.all
    else
      redirect_to new_day_path
    end
  end

  def adminShow
    @user = current_user
    if @user.admin == true
      @days = Days.where(id_param)
      @users = User.all
    else
      redirect_to new_day_path
    end
  end

  def edit
      @days = Days.find_by("id" => id_param[:id])
    end

    def update
      @days = Days.find_by("id" => id_param[:id])
      if @days.update(days_params)
        redirect_to days_path
      else
        redirect_to days_path
      end
    end

    def destroy
      @days = Days.destroy(params[:id])
      ## need to add back deleted days.
      @day = Days.last
      @day.daysLeft += @days.daysTaken
      if @days.save
        redirect_to @days
      end
    end


  private

  def days_params
   params.require(:days).permit(:daysTaken, :daysLeft, :dateTaken, :note, :id)
  end

  def id_param
    params.permit(:id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/days/_daysForm.html.erb
  <div class="col-md-4 col-md-offset-4">
    <div class="row">
      <ul class="days">

          <div class="txt">
            <%= form_for @days do |f| %>

              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :name, :value => current_user.email %>

              <p><%= f.label :daysTaken, 'Number of Days:' %></p>
              <%= f.text_field :daysTaken, class: 'form-control' %>
              <br>

              <p><%= f.label :dateTaken, 'Date:' %></p>
              <%= f.date_field :dateTaken, type: 'date', class: 'form-control' %>
              <br>
              <p><%= f.label :note, 'Notes:' %></p>
              <%= f.text_area :note, class: 'form-control' %>

              <br>
              <%= f.submit "SUBMIT REQUEST", class: 'btn btn-primary btn-block'  %>

            </div>

        </ul>
    </div>
  </div>
<% end %>

app/views/days/_table.html.erb
<div class="container">


  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Days Left</th>
          <th>Requested Days</th>
          <th>Requested Date</th>
          <th>Notes</th>
        </tr>
      </thead>

      <tbody>
        <% @days.each do |f| %>
        <tr>
          <td><%= f.name %></td>
          <td><%= f.daysLeft %></td>
          <td><%= f.daysTaken %></td>
          <td><%= f.dateTaken.strftime("%A %B %d, %Y") %></td>
          <td><%= f.note %></td>
          <% if current_user.admin == true %>
            <td><%= link_to "edit", edit_day_path(f.id) %></td>
            <td><%= link_to "delete", day_path(f.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/days/admin.html.erb
<h1 class="text-center">Days Taken - Admin View</h1>
  <div class="dropdown center-block">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Pick Employee
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <% @users.each do |f| %>

      <li><%= link_to f.name, adminShow_days_path(user_id:f.id) %></li>
      <% end %>
    </ul>
  </div>
  <%= render 'table' %>

app/views/days/adminShow.html.erb
<h1 class="text-center">Days Taken - <%= @days.last.name %></h1>
<div class="dropdown center-block">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Pick Employee
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <% @users.each do |f| %>

    <li><%= link_to f.name, adminShow_days_path(user_id:f.id) %></li>
    <% end %>
  </ul>
</div>
  <%= render 'table' %>

app/views/days/edit.html.erb
<%= render 'daysForm' %>

app/views/days/index.html.erb
<div class="blue">
  <div class="row vdivide">
    <div class="col-md-6 top">
      <img src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAS9AAAAJGY2MTRiYTU0LWI5YWQtNDFjYS04Yjk1LWM2NjJhNzA0NzdjNg.jpg" class="center-block img-circle profilePic">
      <h1 class="text-center txt">
        <%= current_user.name %>
      </h1>
    </div>
    <div class="col-md-6 top">
        <h1 class="text-center daysRemaining txt">
          <%= @days.daysLeft %>
        </h1>
      <h1 class="text-center txt">
        Days Given
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <br><br>
      <h1 class="text-center txt"><%= link_to "Request Days", new_day_path %></h1>
      <br>

      <br><br><br>
    </div>
  </div>
</div>
</div>

app/views/days/new.html.erb
<div class="blue">
  <div class="row vdivide">
    <div class="col-md-6 top">
      <img id="employeePic" src= <%= current_user.employeePic %> class="center-block img-circle profilePic">
      <h1 class="text-center txt">
        <%= current_user.name %>
      </h1>
    </div>
    <div class="col-md-6 top">
        <h1 class="text-center daysRemaining txt">

          <%= @day.daysLeft %>

        </h1>
      <h1 class="text-center txt">
        Days Remaining
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <br><br>
      <h1 class="text-center txt">REQUEST DAYS</h1>
      <br>
      <%= render 'daysForm' %>
      <br><br><br>
    </div>
  </div>
</div>

app/views/days/show.html.erb
<h1 class="text-center">Days Taken</h1>
<br>
<div class="text-center">
  <%= link_to "ADD DAY", new_day_path, class: 'btn-lg btn-primary text-center' %>
</div>
  <br>
<%= render 'table' %>

app/views/home/index.html.erb
<div class="row">
  <div class="jumbotron hero-unit jmbotxt text-center">
    <h1>Track your vacation days</h1>
    <h2>
      Use this app to submit requests for vacation and track how many days you have left.
    </h2>

    <br>
    <% if user_signed_in? %>
      <%= link_to "Track PTO", new_day_path, class: 'btn btn-primary btn-lg' %>
    <% else %>
      <%=  link_to "Log in", new_user_session_path, class: 'btn btn-primary btn-lg' %>
    <% end %>
    <br><br>
    <h3>
      #TeamTallience - Thank you for all your hard work and dedication.
    </h3>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-bottom">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="copyright">
            © 2016, Tallience, LLC
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="design">
            <p>made with ❤️ </p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'TALLIENCE', root_path, id: 'logo' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><a href="/days/show">PTO</a></li>
        <li><%= link_to 'Contact Us'  %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="">
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/days/show">History</a></li>
                <% if current_user.admin == true %>
                  <li><%= link_to 'Admin', admin_path %></li>
                <% end %>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 0]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
      <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tallience | Vacation Tracker</title>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <div class="row">
    <img src="https://trademarks.justia.com/media/image.php?serial=85149721" class="img-responive  center-block">
    </div>
    <!-- from Devise tutorial https://www.sitepoint.com/devise-authentication-in-depth/ -->
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
    <% end %>

  <%= yield %>
  </div>
  <!-- yield top content from Devise tutorial -->

  <%= yield :top_content %>
  <%= render 'layouts/footer' %>